### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by BrentonPoke** [AreaFiftyLAN/toornament-client#1]
What still needs to be implemented here? I'm planning on building something for Overwatch and want to start with this, but not sure how far along this is. It looks like you have the authentication down and the skeleton for getting the endpoints, but query-building seems to be missing. Can others contribute to this?

**Comment by skamoen** [comment]
Hi!
Thanks for creating an issue, it's really awesome to see someone actually wanting to use this outside of our little organization!

As stated in the readme, this is very early in development and I wasn't really planning on using this anywhere outside our own usecase. However, if you want to use this, I'm more than willing to speed up development and allow for contributions. 

I have a very busy week ahead of me, but I'll definitely get back to you before the end of next week with a list of stuff to do and a contributor plan.

**Comment by BrentonPoke** [comment]
Sweet. I created a pull request about 5 minutes before you posted. Small additions, but ones that seem to be needed.

edit: I see you responded to it already.

**Comment by skamoen** [comment]
I investigated the Lombok issues, but I didn't found a solution I'm happy with. Easiest solution is to remove Lombok and just use regular getters and setters, which I just did. 

The editorconfig should deal with the odd diffs, and you can add getters and setters where deemed necessary.
