### ISSUE TITLE
General question about gradle

### ISSUE THREAD

**Issue by BrentonPoke** [AreaFiftyLAN/toornament-client#8]
I've been using a basic commandline project with gradle to test the API library, and have been relying on jitpack for gradle. Now for some mysterious reason, Netbeans is stuck resolving a dependency. It looks like this:
![alt text](http://i.imgur.com/Kow3oJy.png "")
There wasn't a problem until I deleted my old branch and tried to get gradle use the new one that's there now. Even my source tree (the one at the top) isn't showing up presumable because it's not loading the project. 
![alt text](http://i.imgur.com/WHqlo3h.png "")
What is going on here?

**Comment by skamoen** [comment]
I use IntelliJ Idea as an editor, never had any issues like this. It seems like a Netbeans issue to me. 

Anyway, for testing the toornament client I add a `com.test` package to the project (without committing it) with a `ToornamentRunner.java` or something, with a main method in which I initialize a client and perform the operations. You can just run that main method containing your testing code

That way you "simulate" an application outside the Toornament package using the client, without having to deal with Gradle or Jitpack. I don't have the code available at the moment, but I can show you in a few hours if needed.
